version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        - name: Something
        - command: echo "//npm.greensock.com/:_authToken=${NPM_TOKEN}" > ~/.npmrc && echo "@gsap:registry=https://npm.greensock.com" >> ~/.npmrc
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      # - run:
      #     name: Run tests
      #     command: npm run test

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
